# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-30 14:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20171226_0045'),
        ('orders', '0003_productinbacket'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyingProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=250)),
                ('is_active', models.BooleanField(default=True)),
                ('numb', models.IntegerField(default=1)),
                ('itemprice', models.DecimalField(decimal_places=5, default=0, max_digits=10)),
                ('totalprice', models.DecimalField(decimal_places=5, default=0, max_digits=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('Order', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.Order')),
                ('product_id', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
            ],
        ),
        migrations.RemoveField(
            model_name='productinbacket',
            name='product',
        ),
        migrations.DeleteModel(
            name='ProductInBacket',
        ),
    ]
