# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-02 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20180101_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyingproduct',
            name='itemprice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='buyingproduct',
            name='totalprice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='productinorder',
            name='itemprice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='productinorder',
            name='totalprice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
