# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-26 00:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20171226_0039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='products',
            new_name='product',
        ),
    ]
